### PR TITLE
Support for `list-an` command

### LINKED ISSUE #12: As a user, I want to be able to list all my patient's appointment note

### PR DESCRIPTION
**Pull request by sebin0817**
Resolves #12
- Modified UI to view both patient's medical records and appointment notes lists

### CODE REVIEW

**Comment by jmsandiegoo** [comment]
Hey sebin awesome work with the ui and the list-an command perhaps you could fix the checkstyle as well whenever possible?

**Review by jmsandiegoo — COMMENTED** [review]
LGTM

**Review by jmsandiegoo — APPROVED** [review]

**Review by joenus — APPROVED** [review]
LGTM, regression still exists for this PR, but I assume it will be fixed in the future.

- Deleting a person should delete the person's note from the master note list.

**Comment by sebin0817** [comment]
With reference to [https://github.com/nus-cs2103-AY2324S2/forum/issues/502], JavaFX classes need not be tested to pass Codecov. Hence closing the PR.  

Nonetheless, an attempt was made leveraging `TestFX` but not integrated as Github Action faces `RuntimeException` from calling the graphics.

**Pull request merged**
